#!/bin/bash

# checking for broken include or include_relative tags
ruby tools/brinclude.rb doc-contents true

# checking for broken internal links
ruby tools/brlinks.rb doc-contents false

# checking for broken external links
ruby tools/brextlinks.rb doc-contents false

# checking for broken external content
ruby tools/brextcontent.rb doc-contents false