[build]
  command = """
    gem install bundler -v 2.5.9
    BUNDLER_VERSION=2.5.9
    pyEnable=$(python -c "import yaml; print(yaml.safe_load(open('_data/buildConfig.yml'))['pyEnable'])")
    if [ "$pyEnable" = "true" ]; then
        # Install pyenv
        curl https://pyenv.run | bash
        # Update PATH
        export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$HOME/.pyenv/versions/3.9.0/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
        # Install Python 3.9.0
        pyenv install 3.9.0
        pyenv global 3.9.0
        # Upgrade pip and install required Python packages
        pip install --upgrade pip
        pip install tensorflow tensorflow-hub numpy pandas markdown transformers langdetect
        # Run pre-build python scripts
        ./tools_py/preBuild-pyScripts
    fi
    bundle exec jekyll build
  """
  publish = "_site/"

[build.environment]
  RUBY_VERSION = "3.1.4"
