#!/bin/bash

# Read the pyEnable value from _data/siteConfig.yml
pyEnable=$(grep 'pyEnable' _data/buildConfig.yml | awk '{print $2}')

# Check if pyEnable is true
if [ "$pyEnable" = "true" ]; then
  # Run the tools_py/test.py script
  ./tools_py/pyScripts
else
  echo "pyEnable is false. Skipping the execution of python scripts."
fi

bundle exec jekyll serve --trace