#!/bin/bash
source tools_sh/colors.sh
source tools_sh/globals.sh

clear
echo ""
print_color "$BOLD_WHITE" "HOLD ON!!! START WORKING ..."
print_color "$BOLD_WHITE" "-------------------------------"


# PYTHON PRE-BUILD SCRIPTS
echo ""
print_color_enclosed "$PURPLE" "PY pre-build scripts"
pyEnable=$(grep 'pyEnable' _data/buildConfig.yml | awk '{print $2}')

if [ "$pyEnable" = "true" ]; then
  ./tools_py/preBuild-pyScripts
else
  echo "pyEnable is false. Skipping the execution of python scripts. Some site features may not be available."
fi

# PRE-FLIGHT CHECKS
# that's good only for local dev environment
# the deployment Github action ignores preFlight check flag
echo ""
print_color_enclosed "$PURPLE" "Doing pre-flight site check"
echo "HEADS UP!!! PRE-FLIGHT CHECK WILL NOT RUN WHEN BUILDING IN PRODUCTION,  IT IS ONLY FOR DEV ..."

preFlight=$(grep 'preFlight' _data/buildConfig.yml | awk '{print $2}')

if [ "$preFlight" = "true" ]; then
  ./check
else
  echo "preFlight check is false. Skipping pre-build site checking. You can always run it manually."
fi
echo ""

print_color_enclosed "$PURPLE" "Time to build the site. Sit back and relax ... "

# just to maintain some compatibility between py and tensorflow
# i.e. on macOS 15 which comes with py 3.13, tensorflow does not work well, so py 3.9.2 must be used
# and a virtual environment is created (named py-dev-env-392)
# comment this line if you use a tensotflow compatible Python version
source ~/py-dev-env-392/bin/activate

# BUILDING THE SITE
bundle exec jekyll clean

# serving on localhost:4000 with the possibility to be accessed from other devices in the same network
LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" bundle exec jekyll serve --incremental --trace --host 0.0.0.0