export const process = {
//dynamic generated code
	env:{
		REACT_PLUGIN_TARGET:"figma_plugin_page_container",
		REACT_WINDOW_SIZE_W:"600",
		REACT_WINDOW_SIZE_H:"300",
		REACT_APP_APP_NAME:"React Figma Plugin Template",
		REACT_MAIN_APP_COMPONENT_TARGET:"Main_App_Root_Div",
		REACT_DEMO_COMPONENT_TARGET:"Demo_Root_Div",
		REACT_DEMO_COMPONENT_2_TARGET:"Demo_2_Root_Div",
		REACT_NAVIGATION_COMPONENT_TARGET:"nav_menu_root_div",
		REACT_CREATE_RECTANGLES:"CREATE_RECTANGLES",
		REACT_REQUEST_REDUX_INITIAL_STATE:"REQUEST_REDUX_INITIAL_STATE",
		REACT_REQUEST_PAGE_NAME:"REQUEST_PAGE_NAME",
		REACT_CLOSE_PLUGIN:"CLOSE_PLUGIN",
		REACT_REDUX_STATE:"REDUX_STATE",
		REACT_UI_RESIZED:"UI_RESIZED",
		REACT_UI_REDUX_SAVED:"UI_REDUX_SAVED",
		REACT_UI_INIT:"UI_INIT",
		REACT_NAVIGATE_MAIN:"NAVIGATE_MAIN",
		REACT_NAVIGATE_SECONDARY:"NAVIGATE_SECONDARY",
		REACT_STORE_INITIAL_STATE:"STORE_INTIAL_STATE",
		REACT_PAGE_NAME:"PAGE_NAME",
		REACT_RESIZE_PLUGIN_WINDOW:"RESIZE_PLUGIN_WINDOW"
	}
//end dynamic generated code

}