name: GitHub Pages
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}'
    steps:
      - uses: actions/checkout@v4
      - name: Prepare tag
        id: prepare_tag
        if: 'startsWith(github.ref, ''refs/tags/'')'
        run: |
          echo "DEPLOY_TAG_NAME=deploy-${TAG_NAME}" >> "${GITHUB_OUTPUT}"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: '${{ secrets.ACTIONS_DEPLOY_KEY }}'
          publish_dir: ./site
          tag_name: '${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}'
          tag_message: 'Deployment ${{ github.ref_name }}'
