name: Copy gh-pages to jekyll-site-template repo

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_TO_DEPLOY_TO_JEKYLL_SITE_TEMPLATE }}
      
      - name: Clone jekyll-site-template
        run: git clone git@github.com:pmc-community/jekyll-site-template.git temp-repo

      - name: Clear jekyll-site-template.git history
        run: |
          git config --global user.name "florinhoinarescu"
          git config --global user.email "florin_hoinarescu@yahoo.com"
          cd temp-repo
          rm -rf *
          git commit -m "Remove all files"
          git push git@github.com:pmc-community/jekyll-site-template.git HEAD:refs/heads/main --force
    
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          repository: pmc-community/figma
          ref: gh-pages

      - name: Push changes to destination repository
        run: |
          git config user.email "florinhoinarescu"
          git config user.name "florin_hoinarescu@yahoo.com"
          git pull --rebase git@github.com:pmc-community/jekyll-site-template.git
          git push git@github.com:pmc-community/jekyll-site-template.git HEAD:refs/heads/main --force
