name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Check if Python is enabled
        id: check-py-enable
        run: |
          pyEnable=$(grep -Po 'pyEnable:\s*\K(true|false)' _data/siteConfig.yml)
          echo "::set-output name=pyEnable::$pyEnable"
        shell: bash

      - name: Setup Python (conditionally)
        if: steps.check-py-enable.outputs.pyEnable == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies (conditionally)
        if: steps.check-py-enable.outputs.pyEnable == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow tensorflow-hub numpy pandas markdown

      - name: Run Python script (conditionally)
        if: steps.check-py-enable.outputs.pyEnable == 'true'
        run: |
          python3 tools_py/test.py

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
          TEST_VAL: ${{ secrets.TEST_VAL }}
          JEKYLL_ACCESS_TOKEN: ${{ secrets.JEKYLL_ACCESS_TOKEN }}
          JEKYLL_GIT_USER: ${{ secrets.JEKYLL_GIT_USER }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
