name: Copy (with Exclusions) Last Commit of gh-pages Branch

on:
  workflow_dispatch:

jobs:
  copy-last-commit:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: pmc-community/figma
          ref: gh-pages

      # Step 2: Configure Git and prepare destination repository
      - name: Prepare destination repository
        run: |
          git config --global user.name 'florinhoinarescu'
          git config --global user.email 'florin_hoinarescu@yahoo.com'
          git clone https://github.com/pmc-community/jekyll-site-template.git ../destination-repo
          cd ../destination-repo
          git checkout -B main

      # Step 3: Copy files from source to destination
      - name: Copy last commit content
        run: |
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='doc-raw-contents/' \
            --exclude='doc-change-log/' \
            --exclude='unused/' \
            --exclude='.github/workflows/*' \
            --include='.github/workflows/deploy-site.yml' \
            --exclude='doc-contents/*' \
            --include='doc-contents/general/' \
            --include='doc-contents/_tools/' \
            $GITHUB_WORKSPACE/ ../destination-repo/

          # Commit and push changes
          cd ../destination-repo
          git add --all
