name: Copy (with Excludes) Last Commit of gh-pages Branch

on:
  workflow_dispatch:

jobs:
  copy-last-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: pmc-community/figma
          ref: gh-pages

      - name: Prepare destination repository
        run: |
          git config --global user.name 'florinhoinarescu'
          git config --global user.email 'florin_hoinarescu@yahoo.com'
          git clone https://github.com/pmc-community/jekyll-site-template.git ../destination-repo
          cd ../destination-repo
          git checkout -B main

      - name: Copy last commit content
        run: |
          # Use rsync to copy content with exclusions and inclusions
          rsync -av --delete \
            --include='.github/workflows/deploy-site.yml' \
            --include='doc-contents/general/' \
            --include='doc-contents/_tools/' \
            --exclude='.git' \
            --exclude='doc-raw-contents/' \
            --exclude='doc-change-log/' \
            --exclude='unused/' \
            --exclude='.github/workflows/*' \
            --exclude='doc-contents/*' \
            ./ ../destination-repo/

          # Navigate to the destination repository
          cd ../destination-repo
          git status

      - name: Commit and push changes
        run: |
          cd ../destination-repo
          git add --all
          git commit -m "Sync last commit from gh-pages branch of pmc-community/figma" || echo "No changes to commit"
          git push -f https://x-access-token:${{ secrets.PAT_COPY_GHPAGES_TO_JEKYLL_SITE_TEMPLATE_MAIN }}@github.com/pmc-community/jekyll-site-template.git main

      - name: Clean up
        run: |
          rm -rf ../destination-repo
