name: Copy gh-pages branch

on:
    workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: pmc-community/figma
          ref: gh-pages

      - name: Prepare destination repository
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://github.com/pmc-community/jekyll-site-template.git destination-repo
          cd destination-repo
          git checkout -B main
          git rm -rf .

      - name: Copy contents to destination repository
        run: |
          cp -r . ../destination-repo
          cd ../destination-repo
          git add .
          git commit -m "Update from gh-pages branch of pmc-community/figma repository"
          git push -f origin main

      - name: Clean up
        run: |
          rm -rf destination-repo
